# Generated by Django 3.2.3 on 2021-05-18 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('artistic_nickname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_song', models.CharField(max_length=255)),
                ('youtube_url', models.URLField(default='Not added')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestAPI.artist')),
            ],
        ),
    ]
